### ISSUE TITLE
d_rad0_dt may be unitialized in this function

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#10]
d_rad0_dt may be used before it is set

https://github.com/AER-RC/RRTMG_LW/blob/6e8786ab7b1a3bd3c44fad5bca01335f04c44207/src/rrtmg_lw_rtrnmr.f90#L672

d_rad0_dt is set only in line 657, when idrv .eq. 1

what default value for d_rad0_dt should be used NaN, Zero or whatever?

There are also lots of uninitailized vars used in computations.

What value should they be initialized to?
I have Intel compiler and it supports initializeng vars to zero with /Qinit:zero or to NaN /Qinit:snan

**Comment by mjiacono** [comment]
All of the variables with the suffix "_dt" that are defined in rrtmg_lw_rtrn.f90, rrtmg_lw_rtrnmc.f90 and rrtmg_lw_rtrnmr.f90 are only used when idrv .eq. 1.  The code does not allow d_rad0_dt to be used before it is defined, but it won't affect the result if d_rad0_dt is initialized to zero (where the other variables with the "_dt" suffix are initialized in these modules) in order to satisfy the concerns of particular compilers. This initialization will be added to the next release of the model.
