### ISSUE TITLE
RRTM LW cloud optical properties

### ISSUE THREAD

**Issue by bwalkowiak** [AER-RC/RRTMG_LW#12]
Hello, 

I am curious if I can ask a question regarding RRTM in this GitHub? Specifically, I am trying to model scattering and absorption so I am using the DISORT code option. When I try to run the RRTM LW code with the IN_CLD_RRTM input containing the optical properties of an aerosol over two layers, I receive this error: 

******* ERROR >>>>>>  QGAUSN--max iteration count 

I am able to run the code and receive the output file when I do not use DISORT, but i am very interested in the scattering contribution of my input aerosols. I will attach the file I am using for the optical properties. Thanks!

[aod_for_incld_wd11_0p3.txt](https://github.com/AER-RC/RRTMG_LW/files/9285641/aod_for_incld_wd11_0p3.txt)

**Comment by pernak18** [comment]
@bwalkowiak sure! thank you for our interest in our models. our group does also have an RRTM_LW repo, but until this morning it was private. since you've reminded me of its visibility, i have made it [public](https://github.com/AER-RC/RRTM_LW/), along with the corresponding [RRTM_SW](https://github.com/AER-RC/RRTM_SW) repo. have a look.

and for better consistency/documentation, would you mind copying this issue into RRTM_LW issue tracking? i'll then assign to the appropriate developer and close this one.

please and thanks

**Comment by bwalkowiak** [comment]
Great ! I will move to the Issue to RRTM_LW.
