### ISSUE TITLE
Downward flux in output_rrtm_ICRCCM_sonde

### ISSUE THREAD

**Issue by drbel8** [AER-RC/RRTMG_LW#14]
hello,
I have a question regarding one of the examples:
run_examples_std_atm)/output_rrtm_ICRCCM_sonde

When I compare the output of the same example run by RRTM_LW (v3.3) the resulting downward flux and net flux are very different:
RRTM lowest level:    0      973.6        406.2205      310.9624        95.2581065           -1.35171
RRTM_G lwst level:    0      973.6        406.2213      106.5797       299.6415589           -0.75080

This seems to me the only example that gives such a big difference between the two programs, what is the cause?

**Comment by mjiacono** [comment]
This looks like a somewhat obscure input issue. When IATM=1, RRTM and RRTMG use a companion module called RRTATM to read the user-defined atmosphere. The input file input_rrtm_ICRCCM_sonde sets the water vapor to units of mass mixing ratio (g/kg) identified by the JCHAR setting “C” in the line above each line that specifies the molecular amounts, while the other trace gases are input in units of ppmv (JCHAR = “A”). It appears that RRTMG is using an older version of RRTATM that’s incorrectly reading in the water vapor in those units. The output differences reported were a result of the water profile not being input correctly for this file. I converted the water amounts to ppmv and changed JCHAR to “A” for water to create the attached file. Using this file, RRTMG and RRTM now provide the expected similar results. We will investigate the RRTATM issue and fix in a future release. 

Note that there is another small difference between the models in play in this case. This input file sets NUMANGS to “3”, which means that RRTM will use three angles to perform the flux integration. RRTMG ignores this setting, since it is limited to using just the single diffusivity angle to perform the flux integration. However, RRTMG has a built-in modification that slightly adjusts the diffusivity angle by band relative to the total column water amount, and with this adjustment active, which is always the case, RRTMG can more closely reproduce the 3-angle result provided by RRTM. 

[input_rrtm_ICRCCM_sonde_h2o_ppmv.txt](https://github.com/AER-RC/RRTMG_LW/files/11546652/input_rrtm_ICRCCM_sonde_h2o_ppmv.txt)

**Comment by drbel8** [comment]
Thank you for the explanation
