### ISSUE TITLE
Cloud overlap computation in mcica_subcol_gen_lw.1col.f90 for icld 4 and 5 are identical

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#9]
case (4) and case(5) are identical

https://github.com/AER-RC/RRTMG_LW/blob/6e8786ab7b1a3bd3c44fad5bca01335f04c44207/src/mcica_subcol_gen_lw.1col.f90#L577

**Comment by mjiacono** [comment]
This is not an error, but the blocks of code for case (4), exponential cloud overlap, and case (5), exponential-random cloud overlap, in subroutine generate_stochastic_clouds could be consolidated here, since the stochastic procedure for these two cases is identical at this stage. The distinction between exponential and exponential-random cloud overlap is built into the alpha parameter, which is generated by subroutine get_alpha prior to its use in this stochastic procedure.
